# Site settings

title: Blog
description: Personal Blog

email: koko@rhyndo.com
baseurl: "/blog" #  /blog the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

future: true
markdown: kramdown
plugins:
  - jekyll-feed

destination: docs

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package.json
  - package-lock.json
  - .vscode